# Generated by Django 5.0.1 on 2024-01-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_geographypage_delete_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographypage',
            name='text',
        ),
        migrations.AddField(
            model_name='geographypage',
            name='table',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Данные для таблицы (Общая (Год, зарплата))'),
        ),
        migrations.AlterField(
            model_name='geographypage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Общая статистика (Год, зарплата)'),
        ),
    ]
