# Generated by Django 5.0.1 on 2024-01-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_geographypage_text_geographypage_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographypage',
            name='table',
            field=models.FileField(upload_to='uploads/', verbose_name='Данные для таблицы (Общая (Год, зарплата))'),
        ),
    ]
