# Generated by Django 5.0.1 on 2024-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_demandpage_remove_geographypage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandpage',
            name='table_first',
        ),
        migrations.RemoveField(
            model_name='demandpage',
            name='table_fourth',
        ),
        migrations.RemoveField(
            model_name='demandpage',
            name='table_second',
        ),
        migrations.RemoveField(
            model_name='demandpage',
            name='table_third',
        ),
        migrations.AddField(
            model_name='demandpage',
            name='table_all',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='1.3 Год/зарплата/количество (общая) таблица'),
        ),
        migrations.AddField(
            model_name='demandpage',
            name='table_vac',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='4.1 Год/зарплата/количество (для профессии) таблица'),
        ),
        migrations.AlterField(
            model_name='demandpage',
            name='chart_second',
            field=models.ImageField(upload_to='images', verbose_name='1.1 Год/количество (общая)'),
        ),
    ]
