# Generated by Django 5.0.1 on 2024-01-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_demandpage_table_first_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_0_1', models.ImageField(upload_to='images', verbose_name='Навыки 2015 (общее)')),
                ('chart_0_2', models.ImageField(upload_to='images', verbose_name='Навыки 2016 (общее)')),
                ('chart_0_3', models.ImageField(upload_to='images', verbose_name='Навыки 2017 (общее)')),
                ('chart_0_4', models.ImageField(upload_to='images', verbose_name='Навыки 2018 (общее)')),
                ('chart_0_5', models.ImageField(upload_to='images', verbose_name='Навыки 2019 (общее)')),
                ('chart_0_6', models.ImageField(upload_to='images', verbose_name='Навыки 2020 (общее)')),
                ('chart_0_7', models.ImageField(upload_to='images', verbose_name='Навыки 2021 (общее)')),
                ('chart_0_8', models.ImageField(upload_to='images', verbose_name='Навыки 2022 (общее)')),
                ('chart_0_9', models.ImageField(upload_to='images', verbose_name='Навыки 2023 (общее)')),
                ('table_0_1', models.FileField(upload_to='uploads/', verbose_name='Таблица (общее)')),
                ('chart_1_1', models.ImageField(upload_to='images', verbose_name='Навыки 2015 (профессия)')),
                ('chart_1_2', models.ImageField(upload_to='images', verbose_name='Навыки 2016 (профессия)')),
                ('chart_1_3', models.ImageField(upload_to='images', verbose_name='Навыки 2017 (профессия)')),
                ('chart_1_4', models.ImageField(upload_to='images', verbose_name='Навыки 2018 (профессия)')),
                ('chart_1_5', models.ImageField(upload_to='images', verbose_name='Навыки 2019 (профессия)')),
                ('chart_1_6', models.ImageField(upload_to='images', verbose_name='Навыки 2020 (профессия)')),
                ('chart_1_7', models.ImageField(upload_to='images', verbose_name='Навыки 2021 (профессия)')),
                ('chart_1_8', models.ImageField(upload_to='images', verbose_name='Навыки 2022 (профессия)')),
                ('chart_1_9', models.ImageField(upload_to='images', verbose_name='Навыки 2023 (профессия)')),
                ('table_1_1', models.FileField(upload_to='uploads/', verbose_name='Таблица (профессия)')),
            ],
        ),
    ]
