# Generated by Django 5.0.1 on 2024-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_skillspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.FileField(upload_to='uploads/', verbose_name='Текст')),
                ('image', models.ImageField(upload_to='images', verbose_name='Картинка')),
            ],
        ),
    ]
