# Generated by Django 5.0.1 on 2024-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_mainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
