# Generated by Django 5.0.1 on 2024-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_mainpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='text',
            field=models.FileField(upload_to='uploads/', verbose_name='Текст'),
        ),
    ]
