# Generated by Django 5.0.1 on 2024-01-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_mainpage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
