# Generated by Django 5.0.1 on 2024-01-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_mainpage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='image',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №1'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №2'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №3'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №4'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №5'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_ae',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Иконка after effects'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_fig',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Иконка figma'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_lr',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Иконка lightroom'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image_ps',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Иконка adobe photoshop'),
        ),
    ]
