# Generated by Django 5.0.1 on 2024-01-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_mainpage_image_mainpage_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_ae',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_fig',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_lr',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='image_ps',
        ),
    ]
